// Code generated by ogen, DO NOT EDIT.

package api

// Ref: #/components/schemas/CreateUserRequest
type CreateUserRequest struct {
	Email string `json:"email"`
}

// GetEmail returns the value of Email.
func (s *CreateUserRequest) GetEmail() string {
	return s.Email
}

// SetEmail sets the value of Email.
func (s *CreateUserRequest) SetEmail(val string) {
	s.Email = val
}

// Ref: #/components/schemas/CreateUserResponse
type CreateUserResponse struct {
	Success bool `json:"success"`
}

// GetSuccess returns the value of Success.
func (s *CreateUserResponse) GetSuccess() bool {
	return s.Success
}

// SetSuccess sets the value of Success.
func (s *CreateUserResponse) SetSuccess(val bool) {
	s.Success = val
}

// Ref: #/components/schemas/PingResponse
type PingResponse struct {
	Messages string `json:"messages"`
}

// GetMessages returns the value of Messages.
func (s *PingResponse) GetMessages() string {
	return s.Messages
}

// SetMessages sets the value of Messages.
func (s *PingResponse) SetMessages(val string) {
	s.Messages = val
}
