// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateUser implements createUser operation.
//
// Create user.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserRequest) (r *CreateUserResponse, _ error) {
	return r, ht.ErrNotImplemented
}
